### ISSUE TITLE
Missing binary release or up-to-date build instructions.

### ISSUE THREAD

**Issue by atteneder** [KhronosGroup/glTF-Compressonator#3]
I'm eager to try the CLI tools on macOS and Linux, but I failed to build them on either.

I tried the scripts in `Compressonator/Applications/CompressonatorCLI/Make/`, but they fail and I ran from fixing one include after the other.

On Linux I gave up at the KTX library ( it cannot find `#include <vulkan/vulkan.h>`)

On macOs the out-dated brew formula qt@5.5 is used and again lots of includes don't work.

I know this project is in an early phase, but making it accessible to users/devs is crucial imho. Of course I'm willing to help and report more details, if asked for.

**Comment by UX3D-nopper** [comment]
see https://github.com/KhronosGroup/glTF/pull/1612#issuecomment-554647528

**Comment by donmccurdy** [comment]
This repository is being archived — please direct comments to https://github.com/KhronosGroup/KTX-Software/, or https://github.com/GPUOpen-Tools/compressonator, instead. Thanks!
